// Auto-generated by `bun scripts/embed-web.ts` — do not edit manually.
// Empty in dev mode (falls back to filesystem). Populated at build time.
export const WEB_ASSETS: Record<string, string> = {};
