export function getCodeMapReadme() {
  return [
    "# CodeMap generative UI guidelines",
    "",
    "你现在处于一个专门为 CodeMap / 架构链路可视化准备的生成式插件环境。",
    "",
    "## 推荐工作流",
    "### 视觉优先（默认）",
    "1. 先调用 `codemap_read_me`（当前工具）了解规范",
    "2. 再调用 `codemap_collect_context` 收集代码与文档上下文",
    "3. 基于上下文生成 CodeMap 结构",
    "4. 直接调用 `codemap_show_widget`，优先传 `widget_code`，让 HTML 以渐进流式方式披露给用户",
    "5. 正常情况下不要让用户去运行命令，命令仅留给运维和调试",
    "",
    "### 需要落盘/导出时",
    "1. 先按上面的步骤生成结构",
    "2. 调用 `codemap_render_html` 产出 JSON + HTML 文件",
    "3. 如仍需要视觉预览，再调用 `codemap_show_widget` 打开落盘结果或直接展示 HTML",
    "",
    "## CodeMap 目标结构",
    "- title: 主标题",
    "- description: 全局说明",
    "- mermaidDiagram: 全局 Mermaid 图（可选但强烈推荐）",
    "- traces: 链路数组，每条 trace 至少包含：",
    "  - id",
    "  - title",
    "  - description",
    "  - locations[]: 关键定位点（path / lineNumber / lineContent / title / description）",
    "  - traceTextDiagram: 文本调用图",
    "  - traceGuide: 阅读要点，建议 3~5 条",
    "",
    "## 生成原则",
    "- 先总览，再分 trace，不要一上来就只给局部细节",
    "- location 要尽量落到真实文件和真实方法",
    "- trace 要能回答“入口在哪里、编排在哪里、真实收口在哪里”",
    "- 如果是支付/订单/状态机类问题，重点区分主链、回调链、补偿链、设备侧链",
    "- 不要盲猜代码位置，先收集上下文再生成",
    "",
    "## HTML 渲染原则",
    "- 默认先生成适合 `widget_code` 的 HTML 片段，便于渐进式流式披露",
    "- 需要持久化时再生成独立 HTML 页面，供本地端口和 Glimpse 窗口复用",
    "- 页面至少要有：总览、trace tabs、Mermaid 图、文本调用图、定位点列表",
    "- 结构优先于炫技，页面用于理解链路，不是做 marketing landing page",
    "",
    "## widget_code 输出模板",
    "- 输出 HTML fragment，不要带 DOCTYPE / html / head / body",
    "- 建议顺序：style → hero → tabs → layout → script",
    "- fragment 里要有可点击定位点，并向外发 `codemap-location-click` 事件",
    "- 默认先出可视结果，只有用户说保存/导出时再考虑 `codemap_render_html(persist=true)`",
    "",
    "示例骨架：",
    "```html",
    "<style>/* 最小样式 */</style>",
    "<div class=\"cmg-root\">",
    "  <section class=\"cmg-hero\">...</section>",
    "  <div class=\"cmg-tabs\" id=\"cmgTabs\"></div>",
    "  <section class=\"cmg-layout\">",
    "    <div id=\"cmgDiagram\"></div>",
    "    <div id=\"cmgLocations\"></div>",
    "  </section>",
    "</div>",
    "<script>",
    "  function emitLocationClick(location){",
    "    const payload = { type:'codemap-location-click', location };",
    "    if (window.parent && window.parent !== window) window.parent.postMessage(payload, '*');",
    "    if (window.glimpse && typeof window.glimpse.send === 'function') window.glimpse.send(payload);",
    "  }",
    "<\/script>",
    "```",
    "",
    "## Tool 路由建议",
    "- 用户说“扫描链路 / 生成 codemap / 可视化流程 / 架构图 / 状态机图”时，优先考虑这套工具链",
    "- 如果用户已经给了 CodeMap JSON 或 HTML，则可以直接走渲染路径，而不是重新收集上下文",
  ].join("\n");
}
