#!/usr/bin/env bun
/**
 * Reads web UI files and generates `src/_web-assets.ts` with embedded content.
 * Source of truth is admin-console/dist produced by vite build.
 * Run before `bun build --compile` to bake web assets into the binary.
 */
import { readFileSync, writeFileSync, readdirSync, cpSync, rmSync } from "node:fs";
import { join } from "node:path";

const distDir = join(import.meta.dir, "../admin-console/dist");
const webDir = join(import.meta.dir, "../src/web");
const outFile = join(import.meta.dir, "../src/_web-assets.ts");

rmSync(webDir, { recursive: true, force: true });
cpSync(distDir, webDir, { recursive: true });

const files = readdirSync(webDir).filter(f => !f.startsWith("."));
const entries: string[] = [];

for (const file of files) {
  const content = readFileSync(join(webDir, file), "utf-8");
  entries.push(`  ${JSON.stringify(file)}: ${JSON.stringify(content)}`);
}

const code = `// Auto-generated by scripts/embed-web.ts — do not edit manually.
export const WEB_ASSETS: Record<string, string> = {
${entries.join(",\n")},
};
`;

writeFileSync(outFile, code);
console.log(`Synced ${files.length} web assets from admin-console/dist → src/web and embedded into src/_web-assets.ts`);
