#!/usr/bin/env bun
/**
 * Reads web UI files and generates `src/_web-assets.ts` with embedded content.
 * Run before `bun build --compile` to bake web assets into the binary.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const webDir = join(import.meta.dir, "../src/web");
const outFile = join(import.meta.dir, "../src/_web-assets.ts");

const files = readdirSync(webDir).filter(f => !f.startsWith("."));
const entries: string[] = [];

for (const file of files) {
  const content = readFileSync(join(webDir, file), "utf-8");
  entries.push(`  ${JSON.stringify(file)}: ${JSON.stringify(content)}`);
}

const code = `// Auto-generated by scripts/embed-web.ts — do not edit manually.
export const WEB_ASSETS: Record<string, string> = {
${entries.join(",\n")},
};
`;

writeFileSync(outFile, code);
console.log(`Embedded ${files.length} web assets → src/_web-assets.ts`);
